# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96804555ae6dab08cf22724f1b7444d6dde35d22f33a839ef14d256081217c22c8d631880cca98165a7900c5f7a5458bc4ce8daafc159315e6d13da4d38f3339

test:
  secret_key_base: aeb90071a976723d69900dd2024d5e350d375ffec906a7fdff7d1c2b1d17d71674ccb5367374b768a191686a714b9ccc76d852f19e6cfb8bad83cd246dc88404

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
